CREATE DATABASE IF NOT EXISTS eys_db;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    passwd_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);